### ISSUE TITLE
As a beacon Project Manager I want that the Beacon Südtirol Adventure app uses the production API in order to be independent from the one of Belka.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/beacon-gamification-app#8]
During the publication we have to check also that the Gamification module is pointing on the right production API.

**Comment by alexlanz** [comment]
@sseppi Should we add the same data (SQL and S3) as for the test environment by coping everything over? Or should I leave everything blank to start from scratch on the production environment?

**Comment by sseppi** [comment]
@alexlanz , if possible, on the production server we should start from the same content that has been published on the Belka's server. this means the CAstel Mareccio, NOI and Merano Game.
Do you think it is possible?

**Comment by alexlanz** [comment]
This should be done now.

**Comment by alexlanz** [comment]
@sseppi The app is now deployed and published at the alpha channel. Could you please test it if everything works?

**Comment by sseppi** [comment]
The gamification backend is now online on production:
https://gamification.beacon.bz.it/
The Gamification App is also taking the data from the production backend.
